# 添加源设备
post http://localhost:3000/device?device_type=source
Content-Type: application/json

{
  "name": "source",
  "type": "s3",
  "protocol": "Minio",
  "ak": "minioadmin",
  "sk": "minioadmin",
  "endpoint": "http://localhost:9000"
}

###
# 添加目标设备
post http://localhost:3000/device?device_type=target
Content-Type: application/json

{
  "name": "target",
  "type": "s3",
  "protocol": "Minio",
  "ak": "minioadmin",
  "sk": "minioadmin",
  "endpoint": "http://localhost:9000"
}

###
# 获取源设备
get http://localhost:3000/device/?device_type=source

###
# 获取目标设备
get http://localhost:3000/device/?device_type=target

### 
#模糊搜索
# get http://localhost:3000/device/?device_type=target&name=source

###
# 编辑设备
put http://localhost:3000/device/1
Content-Type: application/json

{
  "name": "target",
   "type": "s3",
  "protocol": "Minio",
  "ak": "minioadmin",
  "sk": "minioadmin",
  "endpoint": "http://localhost:9000"
}

###
#删除设备
DELETE http://localhost:3000/device/3

###