# 创建任务
POST http://localhost:3000/task
Content-Type: application/json

{
  "name": "test",
  "source_device_id": 1,
  "source_bucket_name": "my-bucket",
  "source_url": "test",
  "target_device_id": 2,
  "target_bucket_name": "another-bucket",
  "target_url": "test",
  "concurrent": 1,
  "limit_speed": 0,
  "increment_circle": 0
}

### 
# 获取任务
get http://localhost:3000/task/10

###
# 删除任务
DELETE http://localhost:3000/task/1

###
DELETE http://localhost:3000/task/